<?php
namespace MarketingAgent\Database;

use PDO;

/**
 * Schema Builder — generates CREATE TABLE / ALTER TABLE DDL
 * that is syntactically correct for each supported database driver.
 *
 * Supported drivers: sqlite | mysql | pgsql | sqlsrv | oracle
 */
class Schema {
    private PDO    $pdo;
    private string $driver;

    public function __construct(PDO $pdo) {
        $this->pdo    = $pdo;
        $this->driver = strtolower($pdo->getAttribute(PDO::ATTR_DRIVER_NAME));
    }

    // ─── Public column-name quoting ────────────────────────────────
    public function quoteColumn(string $col): string {
        return match ($this->driver) {
            'mysql'  => "`{$col}`",
            'sqlsrv' => "[{$col}]",
            default  => "\"{$col}\"",   // pgsql, oracle, sqlite
        };
    }

    // ─── Public table-name quoting ─────────────────────────────────
    public function quoteTable(string $table): string {
        return $this->quoteColumn($table);   // same rules
    }

    // ─── Auto-increment primary key DDL fragment ───────────────────
    public function primaryKeyDdl(): string {
        return match ($this->driver) {
            'mysql'  => 'INT AUTO_INCREMENT PRIMARY KEY',
            'pgsql'  => 'SERIAL PRIMARY KEY',
            'sqlsrv' => 'INT IDENTITY(1,1) PRIMARY KEY',
            'oracle' => 'NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            default  => 'INTEGER PRIMARY KEY AUTOINCREMENT',   // sqlite
        };
    }

    // ─── VARCHAR DDL (MySQL requires explicit length on index cols) ─
    public function varcharDdl(int $len = 255): string {
        return "VARCHAR({$len})";
    }

    // ─── TEXT DDL (no defaults on MySQL TEXT; use VARCHAR instead) ─
    public function textDdl(): string {
        return match ($this->driver) {
            'oracle' => 'CLOB',
            default  => 'TEXT',
        };
    }

    // ─── DATETIME / TIMESTAMP DDL ──────────────────────────────────
    public function datetimeDdl(bool $withDefault = false): string {
        $type = match ($this->driver) {
            'sqlsrv' => 'DATETIME2',
            'oracle' => 'TIMESTAMP',
            default  => 'DATETIME',
        };
        if (!$withDefault) return $type;
        $default = match ($this->driver) {
            'sqlsrv' => 'GETDATE()',
            'oracle' => 'CURRENT_TIMESTAMP',
            default  => 'CURRENT_TIMESTAMP',
        };
        return "{$type} DEFAULT {$default}";
    }

    // ─── IF NOT EXISTS guard ────────────────────────────────────────
    public function createTableIfNotExists(string $table, string $columnDdl): void {
        $qt = $this->quoteTable($table);
        if ($this->driver === 'oracle') {
            // Oracle does not support IF NOT EXISTS — use exception guard
            try {
                $this->pdo->exec("CREATE TABLE {$qt} ({$columnDdl})");
            } catch (\PDOException $e) {
                // ORA-00955 = table already exists
                if (strpos($e->getMessage(), 'ORA-00955') === false) {
                    throw $e;
                }
            }
        } elseif ($this->driver === 'sqlsrv') {
            $sql = "IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='{$table}' AND xtype='U')
                    CREATE TABLE {$qt} ({$columnDdl})";
            $this->pdo->exec($sql);
        } else {
            $this->pdo->exec("CREATE TABLE IF NOT EXISTS {$qt} ({$columnDdl})");
        }
    }

    // ─── ADD COLUMN IF NOT EXISTS ──────────────────────────────────
    public function addColumnIfNotExists(string $table, string $column, string $typeDdl): void {
        $qt = $this->quoteTable($table);
        $qc = $this->quoteColumn($column);

        if ($this->driver === 'pgsql') {
            // PostgreSQL 9.6+ supports ADD COLUMN IF NOT EXISTS
            try {
                $this->pdo->exec("ALTER TABLE {$qt} ADD COLUMN IF NOT EXISTS {$qc} {$typeDdl}");
            } catch (\PDOException $e) {}
        } elseif ($this->driver === 'sqlsrv') {
            $sql = "IF NOT EXISTS (
                        SELECT * FROM INFORMATION_SCHEMA.COLUMNS
                        WHERE TABLE_NAME='{$table}' AND COLUMN_NAME='{$column}'
                    ) ALTER TABLE {$qt} ADD {$qc} {$typeDdl}";
            try { $this->pdo->exec($sql); } catch (\PDOException $e) {}
        } elseif ($this->driver === 'oracle') {
            try {
                $this->pdo->exec("ALTER TABLE {$qt} ADD {$qc} {$typeDdl}");
            } catch (\PDOException $e) {
                // ORA-01430 = column already exists in table
                if (strpos($e->getMessage(), 'ORA-01430') === false) {
                    throw $e;
                }
            }
        } else {
            // sqlite / mysql — swallow duplicate-column exceptions
            try {
                $this->pdo->exec("ALTER TABLE {$qt} ADD COLUMN {$qc} {$typeDdl}");
            } catch (\PDOException $e) {}
        }
    }

    // ─── UNIQUE index helper ────────────────────────────────────────
    public function addUniqueIndexIfNotExists(string $table, string $indexName, array $columns): void {
        $qCols  = implode(', ', array_map([$this, 'quoteColumn'], $columns));
        $qt     = $this->quoteTable($table);
        if ($this->driver === 'pgsql') {
            try {
                $this->pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS {$indexName} ON {$qt} ({$qCols})");
            } catch (\PDOException $e) {}
        } elseif ($this->driver === 'sqlsrv') {
            $sql = "IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name='{$indexName}')
                    CREATE UNIQUE INDEX {$indexName} ON {$qt} ({$qCols})";
            try { $this->pdo->exec($sql); } catch (\PDOException $e) {}
        } elseif ($this->driver === 'oracle') {
            try {
                $this->pdo->exec("CREATE UNIQUE INDEX {$indexName} ON {$qt} ({$qCols})");
            } catch (\PDOException $e) {}
        } else {
            // sqlite / mysql — just try; swallow if exists
            try {
                $this->pdo->exec("CREATE UNIQUE INDEX IF NOT EXISTS {$indexName} ON {$qt} ({$qCols})");
            } catch (\PDOException $e) {}
        }
    }

    // ─── Upsert (INSERT or UPDATE) ─────────────────────────────────
    /**
     * Execute a database-agnostic upsert.
     *
     * @param string   $table      Table name (un-quoted)
     * @param array    $data       Associative column => value map
     * @param string[] $uniqueCols Columns that form the unique key
     */
    public function upsert(string $table, array $data, array $uniqueCols): void {
        $qt = $this->quoteTable($table);
        $cols = array_keys($data);
        $vals = array_values($data);
        $qCols = implode(', ', array_map([$this, 'quoteColumn'], $cols));
        $placeholders = implode(', ', array_fill(0, count($vals), '?'));

        if ($this->driver === 'pgsql') {
            $conflict = implode(', ', array_map([$this, 'quoteColumn'], $uniqueCols));
            $updates  = implode(', ', array_map(fn($c) => $this->quoteColumn($c) . " = EXCLUDED." . $this->quoteColumn($c), $cols));
            $sql = "INSERT INTO {$qt} ({$qCols}) VALUES ({$placeholders})
                    ON CONFLICT ({$conflict}) DO UPDATE SET {$updates}";
            $this->pdo->prepare($sql)->execute($vals);

        } elseif ($this->driver === 'mysql') {
            $updates = implode(', ', array_map(fn($c) => $this->quoteColumn($c) . " = VALUES(" . $this->quoteColumn($c) . ")", $cols));
            $sql = "INSERT INTO {$qt} ({$qCols}) VALUES ({$placeholders})
                    ON DUPLICATE KEY UPDATE {$updates}";
            $this->pdo->prepare($sql)->execute($vals);

        } elseif ($this->driver === 'sqlsrv') {
            // SQL Server MERGE
            $sourceVals  = implode(', ', array_map(fn($v, $c) => "? AS " . $this->quoteColumn($c), $vals, $cols));
            $onCond      = implode(' AND ', array_map(fn($c) => "t." . $this->quoteColumn($c) . " = s." . $this->quoteColumn($c), $uniqueCols));
            $updatePairs = implode(', ', array_map(fn($c) => "t." . $this->quoteColumn($c) . " = s." . $this->quoteColumn($c), $cols));
            $insertCols  = $qCols;
            $insertSrc   = implode(', ', array_map(fn($c) => "s." . $this->quoteColumn($c), $cols));
            $sql = "MERGE {$qt} AS t
                    USING (SELECT {$sourceVals}) AS s ({$qCols})
                    ON ({$onCond})
                    WHEN MATCHED THEN UPDATE SET {$updatePairs}
                    WHEN NOT MATCHED THEN INSERT ({$insertCols}) VALUES ({$insertSrc});";
            $this->pdo->prepare($sql)->execute(array_merge($vals, $vals));

        } elseif ($this->driver === 'oracle') {
            $sourceVals  = implode(', ', array_map(fn($v) => '?', $vals));
            $srcCols     = implode(', ', array_map([$this, 'quoteColumn'], $cols));
            $onCond      = implode(' AND ', array_map(fn($c) => "t." . $this->quoteColumn($c) . " = s." . $this->quoteColumn($c), $uniqueCols));
            $updatePairs = implode(', ', array_map(fn($c) => "t." . $this->quoteColumn($c) . " = s." . $this->quoteColumn($c), $cols));
            $insertSrc   = implode(', ', array_map(fn($c) => "s." . $this->quoteColumn($c), $cols));
            $sql = "MERGE INTO {$qt} t
                    USING (SELECT {$sourceVals} FROM dual) s ({$srcCols})
                    ON ({$onCond})
                    WHEN MATCHED THEN UPDATE SET {$updatePairs}
                    WHEN NOT MATCHED THEN INSERT ({$srcCols}) VALUES ({$insertSrc})";
            $this->pdo->prepare($sql)->execute(array_merge($vals, $vals));

        } else {
            // SQLite: INSERT OR REPLACE
            $this->pdo->prepare("INSERT OR REPLACE INTO {$qt} ({$qCols}) VALUES ({$placeholders})")->execute($vals);
        }
    }

    // ─── Accessor ──────────────────────────────────────────────────
    public function getDriver(): string { return $this->driver; }
}
